### ISSUE TITLE
units for weight?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#100]
I see these entries in the string file:

``` js
  "lbs": {
    "value": "lbs"
  },
  "pound": {
    "value": "pound"
  },
  "pounds": {
    "value": "pounds"
  },
```

Two related questions for @arouinfar:

(1) The strings "lbs" and "pound" are used in the Shopping screen challenges when "Candy" scene is selected, screenshot below. Issue https://github.com/phetsims/unit-rates/issues/48 says to put a "1" in the denominator for the "Unit Rate?" part of the challenge.  Would it make more sense to use "1 lb" instead of "1 pound"?

![screenshot_01](https://cloud.githubusercontent.com/assets/3046552/19056282/6fa44d98-8985-11e6-8015-662b7323aa2f.png)

(2) The string "pounds" appears in the Shopping Lab rate panel, see screenshot below.  Since "lbs" is used on the scale, shouldn't the same units also be used in the Rate control panel?

![screenshot_03](https://cloud.githubusercontent.com/assets/3046552/19056351/ea92e988-8985-11e6-8e18-9d414737223a.png)

**Comment by arouinfar** [comment]
@pixelzoom In general, we have spelled out all units (eg. miles, hours, dollars) because this sim targets a younger audience. Currently "lbs" is the only unit abbreviation. I think it would be better to replace "lbs" with "pounds".

@amanda-phet can you take a look at this? What do you think? It's also a good idea to reduce the total number of strings (where feasible) because there's a character limitation in the testing URL for translations. The character limit only applies to testing translations, not submitting.

**Comment by pixelzoom** [comment]
I'd be fine with using either "lbs" or "pounds" consistently. I don't think we should mix them - it could be confusing to the student and translators.

**Comment by arouinfar** [comment]
When I made the recommendation to go with "pounds" I considered the weight readout on the scale and the challenge prompts -- both can accommodate a longer string. However, I previously overlooked the label on the double number line. The lower axis label reads "Weight (lbs)". There isn't enough space to switch it to "Weight (pounds)".  We can't remove the unit from the label and go with "Weight" because the markers do not indicate the unit.
![image](https://cloud.githubusercontent.com/assets/8419308/19118967/6c3f5cae-8adb-11e6-9a70-9bf5308fbd7d.png)

I'm somewhat inclined now to keep "lbs", "pound", and "pounds". The abbreviated unit (lbs) would only appear on the double number line label (and possibly the scale readout). The challenge prompts and spinners would read "pounds" (or "pound" for the unit rate prompt). 

I know @pixelzoom has reservations about mixing "lbs" and "pounds", but right now I don't see a way around it. We also mix "$" and "dollars". My proposed usage of "lbs" and "pounds" would mirror the way we've handled the cost. (Namely, using the abbreviation on the double number line and in the scale.)

@ariel-phet when you get the chance can you take a look at this too?

**Comment by pixelzoom** [comment]
> The lower axis label reads "Weight (lbs)". There isn't enough space to switch it to "Weight (pounds)".

Then I'd be concerned about translation.  Are "lbs" and "pounds" likely to be converted to the same string in other languages? If so, then the bottom axis label is going to get awfully tiny.

**Comment by pixelzoom** [comment]
... my point being, if we need to substitute "lbs" for "pounds" in English to make this work, is that a viable solution for other languages?

**Comment by arouinfar** [comment]
> Are "lbs" and "pounds" likely to be converted to the same string in other languages?

I think our translators will recognize that that these strings correspond to an abbreviation and a spelled-out unit. Our translators don't always localize units, but when they do, abbreviated units tend to stay abbreviated (I couldn't find any exceptions to this). I imagine that "lbs" will remain an abbreviation, though it may become something like "kg".

For example, a translator can choose to use euros (€) and kilograms (kg) in the sim. This is a face-level change only. For example, we aren't going to convert the unit rate of purple candy from $5.40/lb to 10.58€/kg. It'll be 5.40€/kg.

**Comment by ariel-phet** [comment]
@arouinfar my personal opinion (and this is just an opinion) is that "lbs" would be fine everywhere for American students. I feel like the target age for this sim is not super young, and there are just so many examples of this abbreviation in our culture, from shopping, to sports, to getting weighed for a physical, I just don't think it will be confusing.

**Comment by amanda-phet** [comment]
Sorry to chime in late... I think using both pounds and lbs is fine. Students learning about unit rates are also learning about units, so this seems like a great way to help them understand it. Teachers often talk about units of measurement before jumping in to unit rates, so it is unlikely that this will confuse any students.

**Comment by arouinfar** [comment]
Discussed in 10/6/16 meeting. The consensus is:
- lbs in the scale
- pounds everywhere else (singular where necessary)
- Change double number line labels "dollars" and "pounds"

**Comment by pixelzoom** [comment]
@arouinfar Please verify in http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.26/unit-rates_en.html.

**Comment by arouinfar** [comment]
Looks good! Closing.
