### ISSUE TITLE
keypad lets you enter syntactically-incorrect cost values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#110]
I find it odd that the keypad lets you enter syntactically-incorrect cost values.  

The 2 most glaring examples:

(1) Enter nothing for the numerator on the double number line, then press Enter.  The value gets set to '0.00'.  (Recommendation: Enter key should be disabled, or should do nothing, until something has been entered.)

(2) Enter '2.555', then press Enter. The values is (confusingly) rounded to $2.56.  (Recommendation: After entering '2.55', the number keys should be disabled.)

Other values like '2', '2.', '2.5' are syntactically incorrect, but probably OK.

**Comment by arouinfar** [comment]
These are great suggestions @pixelzoom.  

> Other values like '2', '2.', '2.5' are syntactically incorrect, but probably OK.
> I don't want to be too restrictive, so I think we should allow these values as well.

We should:
- Disable the enter key until something has been entered.

<s>Disable the number keys after two decimals have been entered.</s> (See https://github.com/phetsims/unit-rates/issues/110#issuecomment-256998464)
- Allow "syntactically incorrect" values such as '2', '2.', and '2.5' to be entered.

On a somewhat related note, we currently are able to enter a maximum of 4 digits, which can be in the form of '99.72' or '340.2' or '1000'. While these large numbers are always beyond the upper limit of the double number line, both interviewees productively explored large numbers. In particular, one student was eager to buy 2000 lbs of candy for $100 in the Shopping Lab (by manually placing 2000 lbs on the double number line). 

I think we should continue to allow the entry of large numbers, but I wonder if anything needs to be done about the '340.2' or '1000' case. I don't think it's particularly problematic that these numbers cannot have two decimal places, since I think students will tend to enter rounder figures like '500' or '2000'.

**Comment by arouinfar** [comment]
Ack, accidentally submitted the comment... working on editing my previous post.

**Comment by arouinfar** [comment]
Based on the discussion on 10/27, we should tweak this a bit.

Rather than always disabling the number keys after two decimals are entered, we should...
- Limit the number of fruits and "veggies" to the tenths place, e.g. 5.3 apples or 4.2 potatoes. Disable the number keys after one decimal has been entered.
- Limit the weight of the candy bags, the cost of all items, and the hours to the hundredths place, e.g. 0.53 lbs of green candy, $23.78, or 1.75 hours. Disable the number keys after two decimals have been entered.
- Do not allow decimal values for miles. One-mile increments seems sufficient.

**Comment by pixelzoom** [comment]
Our more recent decision was to constrain to 4 digits and 2 decimals (which constrain occurs first) for _all_ values.   We made this decision after discovering that having different numbers of decimal placed for a rates numerator and denominator caused usability problems with the marker editor. And while this results in syntactically incorrect entries in the keypad, that's OK.

These examples demonstrate limitations of what can be entered via the keypad:

"1234" -> constrained to 4 digits, no decimal places can be entered 
"123.4" -> constrained to 4 digits, only 1 decimal place can be entered
"12.34" -> constrained to 4 digits and 2 decimal places
"1.23" -> constrained to 2 decimal placed, only 3 digits can be entered
".12" -> constrained to 2 decimal placed, only 2 digits can be entered

This implementation is demonstrated in the new Shopping screen, in [1.0.0-dev.35](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.35/unit-rates_en.html?showNew).

@arouinfar Please verify the requirements and implementation. If everything looks OK, please close this issue.  Otherwise please describe what needs to be changed.

**Comment by arouinfar** [comment]
👍
