### ISSUE TITLE
markers don't look the same when their state is restored

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#113]
Each item saves the state of its number line.  But when I switch back to an item, it's markers look different - some of them have been scaled down and grayed out.  

Example:
- start sim
- go to Shopping screen
- select Lemons from combo box
- put 2 bags of lemons on the scale
- the markers look like this:

![screenshot_12](https://cloud.githubusercontent.com/assets/3046552/19088815/27a7bcae-8a35-11e6-8421-abeb2c6782f0.png)
- switch to vegetables scene
- switch back to fruits scene
- the markers now look like this, the '1.25' marker is scaled down and grayed out:

![screenshot_13](https://cloud.githubusercontent.com/assets/3046552/19088834/339bf08e-8a35-11e6-9ab6-59382b33da4a.png)

What is going on here?

**Comment by arouinfar** [comment]
This is a bug @pixelzoom. Looks like things were working properly in dev.19.

**Comment by pixelzoom** [comment]
What is supposed to happen? When (if ever) are markers supposed to be scaled down?

**Comment by arouinfar** [comment]
Markers are scaled down if they are not major tick marks. Major tick marks depend on the type of item.

Fruit & "Veggies": major tick marks are an integer number of items (1-16 items)
Candy: major tick marks are 0.1 lbs (0.1-1.6 lbs)
Cars: major tick marks are integer number of hours (max depends on the rate of the car)

Any manually-added line that does not correspond to a major tick would be the smaller gray line. For example, a line at 1.3 apples would be a smaller gray line.

**Comment by pixelzoom** [comment]
@arouinfar said:

> Any manually-added line that does not correspond to a major tick would be the smaller gray line. For example, a line at 1.3 apples would be a smaller gray line.

By "line", I assume you mean markers on the number line. (This sim _desperately_ needs some standardization on terminology.)

What is a "manually-added" line?  I haven't seen any line appear that is the not the result of some user action (entering a value or adding/removing items from scale).  

And for lines that are not "manually-added", do they appear as major tick marks regardless of their value?

**Comment by arouinfar** [comment]
> By "line", I assume you mean markers on the number line.

Yes, though we've never referred to them as "markers" in any of the brainstorming or design meetings. It's a useful term, so we can keep using it, however.

> What is a "manually-added" line? 

There are three ways to add markers to the double number line. 
- Interaction with the scale -- place bags onto the scale (or remove individual fruits from the scale)
- Correctly answer a challenge prompt
- Add a marker using the marker editor

We've referred to the latter option as a "manual" addition because the student has to deliberately place a maker on the double number line. The first two methods add a marker to the double number line as a byproduct of some other action in the sim, making these methods somewhat automatic, by contrast. 

> And for lines that are not "manually-added", do they appear as major tick marks regardless of their value?

Yes, these markers will always be a major tick mark, but that's a byproduct of the design. It's impossible to place a non-integer number of items onto the scale, and none of the challenge prompts correspond to a non-integer number items.

**Comment by pixelzoom** [comment]
@arouinfar said:

> Yes, though we've never referred to them as "markers" in any of the brainstorming or design meetings. 

FYI, "marker" is used throughout the implementation.

**Comment by pixelzoom** [comment]
The new implementation (see new Shopping screen) does not have this problem. No plans to fix the old implementation, since it will eventually be deleted. Closing this issue as "will not fix".
