### ISSUE TITLE
overlapping markers on number line

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#115]
Multiple markers appear at the same location on the number line, and this looks especially bad when the markers have different sizes.

Example:
- start sim
- go to Shopping screen
- put 2 bags of lemons on the scale
- remove lemons from scale until there's 1 remaining on scale
- select vegetables scene
- select fruits scene (to make some markers change scale, see #113)
- enter '7' for "Lemons for $1.75"
- we now have 2 markers at $1.75, one large, one small (screenshot below) which looks very odd

![screenshot_16](https://cloud.githubusercontent.com/assets/3046552/19089470/9ee577be-8a37-11e6-97f5-08b605bcda03.png)

**Comment by arouinfar** [comment]
This is also a bug @pixelzoom, and it's likely related to the other double number line bugs you found this afternoon. As previously noted in #113, the markers shouldn't stagger since they all correspond to an integer number of lemons.  

If a marker corresponding to a challenge prompt answer is already on the double number line (like 7 lemons for $1.75), its color should change from black to green (if unit rate) or blue (if other prompt). An additional line does not need to be added on top. This is working in dev.19.

Alternatively, if the maker editor is used manually add a maker to a location where a marker already exists (e.g. 10 lemons), the new line should overwrite the old line, as described in #50.

**Comment by pixelzoom** [comment]
This is demonstrated in the implementation of the new Shopping screen - duplicate markers are not created.  This will not be addressed in the old implementation.

Closing.
