### ISSUE TITLE
suspicious padding around checkered flag

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#126]
Here's what checkered_flag.png looks like:

![screenshot_37](https://cloud.githubusercontent.com/assets/3046552/19130548/d6a92cc8-8b08-11e6-8a01-55f23cb5c13f.png)

When the transparent padding around this image is removed, the flag doesn't appear at the correct location. There's no reason for this.

**Comment by pixelzoom** [comment]
For comparison, the green flag has no such padding around it and (presumably) manages to appear at the correct location.

![screenshot_38](https://cloud.githubusercontent.com/assets/3046552/19130611/172bf488-8b09-11e6-99f2-4445efc3acf7.png)

**Comment by pixelzoom** [comment]
And both of these should probably be drawn programmatically, rather than requiring image files with wonky padding.

**Comment by arouinfar** [comment]
@pixelzoom I believe DS defined the touch area by using the image bounds. The checkered flag has extra padding to accommodate the cueing arrows (which are part of the touch area). I agree that programmatically drawing the flags would make more sense, but this was not initially possible due to the constraints on DS's time.

**Comment by pixelzoom** [comment]
Thanks @arouinfar, useful info.

**Comment by pixelzoom** [comment]
Padding removed from image, expanded touchArea for finish flag.

I'm going to leave the flags as image files, because (1) the green flag also appears in the "return to start" button icon, and (2) filling the finish flag with the checkered pattern would be a bit of a pain.

Closing.
