### ISSUE TITLE
Semi-duplication of NumberEntryControl in KeypadPanelNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/unit-rates#130]
@jbphet noted a lot of similarity in https://github.com/phetsims/making-tens/issues/76, but there were enough differences that I didn't factor out any of KeypadPanelNode's behavior into scenery-phet's NumberEntryControl.

Should certain code be shared here?

**Comment by pixelzoom** [comment]
@jbphet Can you elaborate on what you had in mind for a common UI component?  Other than having an edit button and a keypad, I don't see these as being very similar. Unit Rates has a value field that is always present, make-a-ten field appears when edit button is pressed.  And clicking in the the value field for Unit Rates is supposed to be equivalent to clicking the edit button - it opens the keypad.

**Comment by jbphet** [comment]
First, I was observing that they look similar, here are some screenshots:

From Make a Ten:
![keypad-mt](https://cloud.githubusercontent.com/assets/3082831/19485533/a986c376-9518-11e6-8163-acd7a097d7da.PNG)

From Unit Rates:
![keypad-ur](https://cloud.githubusercontent.com/assets/3082831/19485556/b7b6813e-9518-11e6-9d67-be7f3f7661fc.PNG)

They also both behave similarly in that the user enters numbers which show up in the display, then the user presses the button at the bottom, at which point the panel disappears and the value seems to be propagated into the model.

> Unit Rates has a value field that is always present, make-a-ten field appears when edit button is pressed.

I just fired up Make a Ten, went to the second screen, pressed the edit button, and the panel with the keypad, value field, and button popped up.  I'm not sure if we are looking at different versions, different portions of the sim, or if I'm missing what you're saying here, but as far as I can tell they look quite similar.

Having said this, if you've looked at the code and feel that there isn't enough overlap to include this with the other common keypad entry panels, I'm fine with that.  Just close the issue and on we go.

**Comment by pixelzoom** [comment]
Thanks for the clarification.  

Looking at the implementations and the screenshots provided above ...

unit-rates.KeypadPanelNode and scenery-phet.NumberEntryControl both add a numeric readout to scenery-phet.NumberKeypad.  The "Submit" button is actually _not_ part of `NumberEntryControl`, it's added separately in make-a-ten.KeyboardPanel. The "Enter"  button _is_ a part of `KeypadPanelNode`. 

My feeling is that both of these features (value display, button to "enter" the value) should be either optional features of NumberKeypad or a subtype that decorates NumberKeypad.  And this issue should be moved to scenery-phet.

@jbphet Your thoughts?

**Comment by pixelzoom** [comment]
Similar keypads with an "enter" button in arithmetic:

![screenshot_53](https://cloud.githubusercontent.com/assets/3046552/19502146/04b1bebe-9568-11e6-9a10-5b37476d9081.png)

and in projectile-motion:

![screenshot_52](https://cloud.githubusercontent.com/assets/3046552/19502124/e46bd59a-9567-11e6-87b5-8ee717f7642c.png)

And in fact there are currently zero usages of NumberKeypad where some similar button isn't required.  That feels like a deficiency in NumberKeypad.

**Comment by jbphet** [comment]
In response to https://github.com/phetsims/unit-rates/issues/130#issuecomment-254684114, I think we should keep NumberKeypad 'pure' and not add a display or an entry button.  Even though we have no usages now without some sort of 'Enter' button, I could easily envision a situation in the future where we want this.  I would therefore favor the idea of a subtype with the enter button and display, but I think that is essentially what NumberEntryControl and KeypadPanelNode are (not subtypes, strictly speaking, but controls that put the keypad, display, and enter button together through composition).

I just looked at unit-rates.KeypadPanelNode, and I think @jonathanolson may have been discouraged from combining this with the others due to some differences in the API for setting and clearing listeners.  Looking at it (but not too deeply), I still feel like these could all be consolidated.  In other words, it seems like we could have one control with a readout, keypad, and enter button that could work for area-builder, making-tens, and unit rates and possibly (as @pixelzoom noted above) arithmetic and projectile-motion too.

**Comment by pixelzoom** [comment]
If such a component exists in time to use it in unit-rates, I'll certainly use it.  But I have no plans (or time) to do the generalization, moving the issue to https://github.com/phetsims/scenery-phet/issues/271.

Closing.
