### ISSUE TITLE
change "Challenges" to "Questions" ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#133]
@arouinfar How would you feel about changing the title of the accordion box in the Shopping screen from "Challenges" to "Questions"?  In other sims, we call them "Challenges" because they tend to be more elaborate/involves.  But these are posed as questions, with fill-in-the-blank answers.   "Questions" is also a little less "heavy", depending on the audience.

**Comment by pixelzoom** [comment]
In context:

![screenshot_58](https://cloud.githubusercontent.com/assets/3046552/19695223/9123385a-9a9f-11e6-9add-9e717859d9cc.png)

**Comment by arouinfar** [comment]
@pixelzoom I like your suggestion. We originally went with "Challenges" because the term is present in other sims. However, I do agree that these prompts are a bit different, and "Questions" may be more appropriate. You can leave the panel titled "Questions" for now, but I'd like to get feedback from the team at design meeting this week.

**Comment by arouinfar** [comment]
Discussed in 10/27/16 design meeting.

"Challenges" and "Questions" are both somewhat dry. We could try a prompt like "Answer It!" or "Solve It!" but that terminology is more cumbersome for a teacher to use in a classroom. 

For now, we'll leave it as "Questions". I'll close this issue, and re-open it if/when we decide to revisit the nomenclature.
