### ISSUE TITLE
String test= double gives inconsistent cost readout

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#183]
The values cost readout on the scale doesn't produce the same number of decimal places when 'doubled'.
Is this a significant problem? @pixelzoom 

**Shopping**
![image](https://cloud.githubusercontent.com/assets/13894380/23729518/89c3fa42-041f-11e7-8b11-1d4938846674.png)

**Shopping Lab**
![image](https://cloud.githubusercontent.com/assets/13894380/23729537/a94d328e-041f-11e7-852b-b982c28550d4.png)

When inputting a ratio that is irregular the thousandths decimal place is grayed out as intended as shown in the second image.

**Comment by pixelzoom** [comment]
This is a known problem with how `stringTest` handles patterns (strings with placeholders, like "${0}").  See https://github.com/phetsims/chipper/issues/413.  Since it's unlikely to be fixed anytime soon, PhET has been generally ignoring this problem when testing sims.  I think it's appropriate to ignore it here too, since it's not a real-world problem.    But thanks for reporting it.

Closing.

**Comment by pixelzoom** [comment]
#159
