### ISSUE TITLE
Flip/edit images where necessary to keep the light source consistent

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#189]
@arouinfar there is a lot of light source mixing with the item images. All fruit are backwards, and other images scattered here and there backwards. For example:

This:
![image](https://cloud.githubusercontent.com/assets/5863899/23870844/8d752c16-07ed-11e7-858f-86fedcc9cffd.png)

Should be flipped to this (image from Proportion Playground, it's slightly different):
![image](https://cloud.githubusercontent.com/assets/5863899/23870867/a10603a4-07ed-11e7-947e-9cd3dfc0fb3b.png)

Keeping in mind that the respective item in each bag should also be flipped.

@arouinfar up to you if you want this done before publication. It would be good for consistency.

**Comment by pixelzoom** [comment]
If this gets fixed, it needs to be fixed in the .ai files, not in the .png files or (worse) by flipping in the code.

Here's the artwork that has inconsistent lighting, these files live in https://github.com/phetsims/unit-rates/tree/master/assets:

apple.ai
apple_bag.ai
lemon.ai
lemon_bag.ai
orange.ai
orange_bag.ai
pear.ai
pear_bag.ai

After the .ai files are modified, I'll need PNG files with the same dimensions that they are now: 

apple.png 63x73
apple_bag.png 138x156
lemon.png 65x49
lemon_bag.png 138x156
orange.png 60x54
orange_bag.png 139x157
pear.png 61x83
pear_bag.png 138x157

**Comment by arouinfar** [comment]
Thanks for the suggestion @phet-steele. I think this is something that @amanda-phet has also brought up at some point. I will update the files in @pixelzoom's comment.

**Comment by arouinfar** [comment]
Reflected artwork has been emailed to @pixelzoom.

**Comment by pixelzoom** [comment]
@arouinfar @phet-steele please verify in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.73/unit-rates_en.html

Last one to verify, please close.

**Comment by pixelzoom** [comment]
@arouinfar noted that the Shopping Lab screen icon also needs to be fixed.

shopping_lab_screen_icon.png, 548x373

**Comment by pixelzoom** [comment]
Shopping Lab screen icon received from @arouinfar, integrated in above commit.  

@arouinfar please verify in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.74/unit-rates_en.html

**Comment by arouinfar** [comment]
:+1:
