### ISSUE TITLE
User suggestion: metric

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/unit-rates#198]
> Love it. Could you do a change units to metric version?

**Comment by oliver-phet** [comment]
Another user:

> In the sim Unit Rate the measure units are dollars, pounds and miles which are used in US. Is it possible to change these units to euros, kilos and kilometres which are used in Europe? 

> Except of the pop-up windows where you can select the color of the candies (in Shopping), in the rest of the sim the term "pounds" used instead of "candies". I think it should be changed.

**Comment by pixelzoom** [comment]
Re metric:
Dollars, pounds and miles are specific to the US English translation. You can use whatever units you want when you translate the sim.

**Comment by pixelzoom** [comment]
Re:
> Except of the pop-up windows where you can select the color of the candies (in Shopping), in the rest of the sim the term "pounds" used instead of "candies". I think it should be changed.

Unlike fruits and vegetables, we're not measuring number of candies, we're measuring the weight of the candy.  @arouinfar can you please craft a response to this?

**Comment by arouinfar** [comment]
@oliver-phet the currency symbol and units can be localized. 

As for this request:
> Except of the pop-up windows where you can select the color of the candies (in Shopping), in the rest of the sim the term "pounds" used instead of "candies". I think it should be changed.

The candy scene deals with the cost per unit <i>weight</i>, not cost per unit item. Replacing "pounds" with "candies" would not be appropriate here. However, <i>pounds</i> could be localized to <i>kilograms</i> at the translator's discretion.

That said, it looks like we don't support en_CA or en_GB in the translation utility, so we don't currently have the mechanism for someone to create a metric localization in English. I spoke with @jbphet and he said that he could add these locales to rosetta, but introducing flavors to the en locale could also create unanticipated side effects. 

I see a few options:
1. Add en_CA and en_GB to the translation utility. I would be comfortable submitting the translations for these locales, as we don't have a trusted translator. The downside here is that our users in Canada or the UK probably won't think to look for a translated version of the sim.
2. Similar to Projector Mode, add a "Metric" checkbox to About > Options. This would add 6 extra string keys: Metric, kilometers, kilogram, kilograms, Kilograms, and kg. Some users may still not find the option, but it would be self-contained within the sim. (And, of course, documented in the Teacher Tips.)
3. Add a "Metric" checkbox to the play area (off by default). This option would be the easiest for the user to locate. However, the Racing Lab screen really does not have the real estate for this, so I would prefer not to go this route. We may also open ourselves up to some pushback for not actually converting the units, which the user may expect.

I'm on the fence between options 1 & 2. Any thoughts @ariel-phet @pixelzoom?

**Comment by pixelzoom** [comment]
@arouinfar said:
>  I spoke with @jbphet and he said that he could add these locales to rosetta, but introducing flavors to the en locale could also create unanticipated side effects.

@jbphet Can you comment on what potential problems this might cause? I would think that en_CA and en_GB would be no different than any other country-specific locale.  And if they do cause problems, that would be a design/implementation deficiency that should be fixed.

> 2. Similar to Projector Mode, add a "Metric" checkbox to About > Options. ...
> 3. Add a "Metric" checkbox to the play area (off by default). 

I am very much opposed to these options because (a) they are not relevant for all locales, and (b) they will require huge changes to the sim.

**Comment by pixelzoom** [comment]
Btw... I'm "very much" opposed because of first-hand experience with implementing a sim that switches between English and metric units.  Glaciers (Java) has such a control.   It was a royal pain to implement. We had disagreement about what the default should be. And with the exception of US English, the English units were irrelevant, but every locale still had to see them.

**Comment by pixelzoom** [comment]
One more reason why I don't like options 2 & 3...  Two very early design decisions for this sim were (1) units would be changed via translation, and (2) there there would be no way to adjust the range of values based on the units.  For example, the track is 200 units long, regardless of what those units are.  If we add the ability to switch between English and metric units inside the sim, then the user may be very confused when their 200 mile track becomes a 200 km track, instead of ~321 km.  Or when 5 lbs of Apples becomes 5 kg, instead of 2.27 kg.

**Comment by ariel-phet** [comment]
Not OK with option 2 & 3 given we cannot afford extra implementation effort in this sim at the moment. @pixelzoom is correct that is was an early and clear design decision to change by translation. Fine with option 1.

**Comment by arouinfar** [comment]
Thanks for your input @pixelzoom @ariel-phet. Option 1 it is.  Looks like we should move this over to rosetta... I'm currently on mobile, so perhaps @pixelzoom or @jbphet can take care of it? Otherwise, I'll open an issue later this evening.

**Comment by pixelzoom** [comment]
I created the Rosetta issue and assigned to @jbphet, see https://github.com/phetsims/rosetta/issues/149.

@oliver-phet Assigning this back to you to report to the customers.

**Comment by oliver-phet** [comment]
Users have been notified.

**Comment by pixelzoom** [comment]
@arouinfar Anything else to do here, or can this be closed?

**Comment by jbphet** [comment]
I added the capability to support additional English locales, and added a Canadian (en_CA) translation that uses metric units, please see https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_en_CA.html.  @arouinfar - please review and, if all looks good, let @oliver-phet know about it and I think we can probably close the issue.

**Comment by arouinfar** [comment]
Thanks @jbphet! Looks great. 

@oliver-phet please share this link with users looking for a metric/$ version of Unit Rates:
https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_en_CA.html

I started a translation for en_GB that uses the £ symbol for currency. Replacing "dollars" with "pounds" feels a bit strange, even though it's correct. Without comparing the DNL to the scale, a user may mistake "pounds" as a weight, especially because kg doesn't appear until the third scene. 

<img width="949" alt="screen shot 2017-04-11 at 12 03 07 pm" src="https://cloud.githubusercontent.com/assets/8419308/24923488/f140e834-1eae-11e7-885e-0db71820c4e3.png">

Alternatively, I could translate "dollars" to "pounds (£)"

<img width="955" alt="screen shot 2017-04-11 at 12 02 45 pm" src="https://cloud.githubusercontent.com/assets/8419308/24923461/dcc401de-1eae-11e7-81a9-60dc091a87a0.png">

@pixelzoom @jbphet do either of you have any thoughts about how we might want to translate "dollars" for en_GB?

**Comment by arouinfar** [comment]
Other alternatives would be to use just the currency symbol on its own or "pounds sterling" which is a bit verbose.

**Comment by pixelzoom** [comment]
@arouinfar asked:
> @pixelzoom @jbphet do either of you have any thoughts about how we might want to translate "dollars" for en_GB?

I think that decision should be left up to the translators.

**Comment by arouinfar** [comment]
@pixelzoom we don't have a trusted translator for en_GB, but we could wait until @oliver-phet receives a request for a metric/£ version of Unit Rates.

**Comment by oliver-phet** [comment]
> @oliver-phet please share this link with users looking for a metric/$ version of Unit Rates:
https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_en_CA.html

Done.

**Comment by pixelzoom** [comment]
@arouinfar said:
> @pixelzoom we don't have a trusted translator for en_GB, but we could wait until @oliver-phet receives a request for a metric/£ version of Unit Rates.

My point is that I can't answer your question.  Anyone's opinion other than the translator's is irrelevant.  I would leave it as is, and let the eventual trusted translator decide whether to modify it.

**Comment by arouinfar** [comment]
Point taken @pixelzoom. I'll leave it be for now. 

@oliver-phet if you get any requests for a metric/£ version of Unit Rates, the en_GB locale is available in the translation utility.
