### ISSUE TITLE
User suggestion: Fractions

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/unit-rates#199]
At our meeting today, it was suggested to consider whether a version with fractions could be made. We should discuss at some point ... no rush. Just logging it as a question.

**Comment by arouinfar** [comment]
Spoke with @kathy-phet about this briefly. 

- Teachers often deal with rates of compound fractions such as $3/4 for 2/3 lb candy.
- Spinners would contain fractions, not decimals.
- Only Lab screens would be included.
- Shopping Lab would be candy-only (pricing for fractional item is not realistic), but could include a combo box for candies with different bag sizes (1/4 lb, 1/3 lb, etc.).
- Racing Lab may use runners instead of cars due to the lower rates. 

I think it'd be worth exploring the idea of Unit Rates: Fractions a bit more. I'm going to unassign myself for now, but perhaps when space opens up in math brainstorming meetings we can have a discussion around the learning goals.

**Comment by pixelzoom** [comment]
This is not a new "version" of the sim. This would be a huge effort, requiring a "redo" of many parts of the sim.  With the exception of the denominator (hours) in Racing Lab, nothing in this sim (model or view) is prepared to handle non-integer values for the numerator or denominator. "Spinners would contain fractions" would present serious real estate challenges in the Racing Lab screen.  And while it wasn't mentioned in https://github.com/phetsims/unit-rates/issues/199#issuecomment-294224336, presumably the double number line (and marker editor?) would need to handle fractions.

**Comment by arouinfar** [comment]
Thanks @pixelzoom.  And yes, the double number line and marker editor would need to handle fractions. 

Math brainstorming meetings are on hold for awhile, and I don't think there's any plan to discuss Unit Rates: Fractions anytime soon. I'll mark as deferred.

**Comment by pixelzoom** [comment]
I highly recommend moving this issue to wherever ideas for new sims are being tracked.  Leaving it here is a recurring cost, since I review all open issues for my sims on a regular basis.

**Comment by arouinfar** [comment]
@amanda-phet @kathy-phet do you have a doc where you keep track of ideas for math sims, where this may be more appropriate?

**Comment by amanda-phet** [comment]
I can put it in a doc where math sim ideas for the DRK12 grant are listed, but this repo was the appropriate place to have this information discussed. However since the sim is not equipped to handle fractions, and it would be an entirely new sim, I am doubtful that it will ever happen. There are many other sim ideas that are more fleshed out that would be higher priority.
