### ISSUE TITLE
"Double Number Line" accordion box is messed up

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#201]
Should look like this, in published version (1.0.3):

![screenshot_337](https://user-images.githubusercontent.com/3046552/29145323-e9ee8356-7d19-11e7-94e6-22581546c035.png)

Currently looks like this in master (marker editor and collapse button partially outside box):

![screenshot_338](https://user-images.githubusercontent.com/3046552/29145351-035408de-7d1a-11e7-83b1-11ce5dbe76d6.png)

**Comment by pixelzoom** [comment]
@jonathanolson suspects that this is related to recent changes that he made to AccordionBox for resizing.  Assigning to him to investigate.

**Comment by jbphet** [comment]
Here is the issue that describes the recent changes to AccordionBox: https://github.com/phetsims/sun/issues/304

**Comment by jonathanolson** [comment]
(looking into it).

**Comment by jonathanolson** [comment]
AccordionBox has always put the content directly on the expandedBox, and I was incorrectly checking the expandedBox's bounds after modifying its rectWidth/rectHeight. Since the initial content was outside of these bounds, those bounds were incorrect and it cascaded.

Fixed by using the selfBounds of the expandedBox to lay out expanded content.

@pixelzoom can you verify?

**Comment by pixelzoom** [comment]
Verified, closing, thanks!
