### ISSUE TITLE
Drag interupted on flags if cueing arrows are present

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/unit-rates#229]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome and Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/1111
When you try to drag a finish flag that has cueing arrows the drag is interrupted almost immediately.
**Steps to reproduce**
1. Go to the third screen
2. If the cueing arrows for the finish line flags are not there, reset all the page to bring them back
3. Use your mouse to try to move one of the flags.

**Visuals**
![interuptdrag](https://github.com/user-attachments/assets/72563b20-197e-43c9-84e0-b3248628e200)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Unit Rates‬
URL: https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.11/phet/unit-rates_all_phet.html
Version: 1.1.0-dev.11 2024-10-01 00:19:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Reproduced in main.  This problem is not present in published version 1.0.32.

The problem is that the cueing arrows are being dragged, and the drag is interrupted when they become invisible. This is a change that was made in common code for https://github.com/phetsims/scenery/issues/1645 (interruptSubtreeInput when a Node becomes invisible).  There is an option that will need to be added to cueArrowsNode to override this default behavior - `interruptSubtreeOnInvisible: false`.

**Comment by pixelzoom** [comment]
@KatieWoe please review in main. Close if OK.

**Comment by KatieWoe** [comment]
Looks good on main
