### ISSUE TITLE
Add refresh/reset button to challenge prompts

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#23]
Make challenge panel larger to fit refresh button. 

Refresh only applies to prompts following unit rate… unit rate stays (whether right or wrong). 

Color-coordinated challenge prompt lines turn to black, no longer special (see above).

**Comment by schmitzware** [comment]
![59174b3e-4f47-11e6-8cfe-1b5f358d35da](https://cloud.githubusercontent.com/assets/694045/17191752/4e861a70-5400-11e6-88c3-e7ad3e92f1c1.png)

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/6c05e604cfff72fd511a97f6bbe89e866a57bcb7

**Comment by schmitzware** [comment]
This re-populates the Challenges with new data (still random at this point). It will also remove all the corresponding number line markers..

**Comment by arouinfar** [comment]
Took a look at master, and the behavior is working except for the unit rate.

> Refresh only applies to prompts following unit rate… unit rate stays (whether right or wrong).

Refresh should clear prompts 2-4 and the associated ticks on the double number line. The only exception would be if the tick mark corresponds to the number of items on the scale. 

For example, a challenge prompt asks for the cost of 4 apples. I place a bag of apples on the scale, and then remove one apple, leaving 4 on the scale. The 4 apple line appears on the double number line in black text. I then answer the challenge prompt correctly, and the line turns blue. If I refresh the challenge prompts, the 4 apple line should switch to black, but stay present, since there are still 4 apples on the scale.

**Comment by schmitzware** [comment]
Gotcha.. thanks!  I'll tweak that this afternoon..

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/5a588323bc38b3af22da0eadecb86729ccc8cdab
Try that out when you get a chance, Amy.

**Comment by arouinfar** [comment]
The unit rate prompt appears to be fixed, but the tick mark issue is still present @schmitzware 

In this situation, the tick mark at 5 apples should remain on the double number line pressing the challenge reset button because there are five apples still on the scale. However, the tick mark would no longer be color-coordinated to the challenge prompts, so it would go back to black. 

![promptrefresh](https://cloud.githubusercontent.com/assets/8419308/17312290/d888159a-580e-11e6-8d5a-b1bb03d21e7f.gif)

**Comment by schmitzware** [comment]
They say the 3rd time's a charm.  Give that a whirl when you get a chance.
https://github.com/phetsims/unit-rates/commit/7514213ec4b2c11f271bd562cfba70e483492800

**Comment by arouinfar** [comment]
Evidently the 3rd time really is the charm @schmitzware! Looks great. Closing.
