### ISSUE TITLE
Pressing Enter on keypad results in a value of '0'

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/unit-rates#235]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Safari 18.0

**Problem description**
While verifying https://github.com/phetsims/unit-rates/issues/234, I noticed that if I press Enter on the keypad without typing in any value, a value of '0' or '$0.00' will appear in the display in the Questions panel. This also happens in rc.1.

This behavior is different than in published. 

**Steps to reproduce**
1. On the Shopping screen, press the Edit button for any of the questions. 
2. Press Enter on the keypad

**Visuals**
<img width="289" alt="Screenshot 2024-10-17 at 8 17 43 AM" src="https://github.com/user-attachments/assets/6d93b142-8f74-4c82-87df-cc428c4b351e">

**Comment by pixelzoom** [comment]
Reproduced.  This problem was introduced between [1.1.0-dev.2](https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.2/unit-rates_en.html) (10/11/2017) and [1.1.0-dev.3](https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.3/phet/unit-rates_all_phet.html) (5/22/2023) -- which was also the case for https://github.com/phetsims/unit-rates/issues/234.

**Comment by pixelzoom** [comment]
Fixed in main and 1.1 branches.  As in the production version, pressing Enter with no value entered results in closing the keypad.

@Nancy-Salpepi please verify. If it looks OK, change the label to fixed-awaiting-deploy.

**Comment by Nancy-Salpepi** [comment]
Looks good!

**Comment by pixelzoom** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/1158 for 1.1.0-rc.2.  It is sufficent to verify on 1 platform. Close if OK.

**Comment by KatieWoe** [comment]
Things look good on rc.2
