### ISSUE TITLE
Suppress decimal on major tick marks for fruits and vegetables

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#39]
From @kathy-phet 

> On the shopping screen, was there a reason we have the decimal on the fruits and vegetable scenes on the lower double number. Line. Seems like just 1,2,3 would be more friendly? Since for those we always talk whole numbers. 

@schmitzware can you please remove the decimal on the major tick marks for the fruit and vegetables? This would affect the Shopping and Shopping Lab screens.

All of the tick marks on the bottom would be 1, 2, 3...
![image](https://cloud.githubusercontent.com/assets/8419308/17784078/4bc47914-6538-11e6-9d42-888473e88f1d.png)

Any manually added tick marks at fractional values of items would still have one decimal place.

**Comment by schmitzware** [comment]
This turns out to be a little more complicated that it appears. I'm using a common PHET UI component which doesn't allow for dynamically changing the number of decimal places to show. This is set once at creation time - for fruit/produce it's 1, for candy it's 2.

Seems it would be best to add this functionality there, rather than doing a custom UI component just for Unit Rates, however doing so will need to push changes down into Phet-IO also which doesn't look to support some similar needs.

I'll need to ask the other devs on the best way to add this or think of another way to scoot around the problem.

**Comment by arouinfar** [comment]
Let's discuss this at design meeting @schmitzware.

**Comment by kathy-phet** [comment]
It's desirable but lower priority than other progress, so I would vote for putting as low priority for know.
K

Sent from my iPhone

On Aug 24, 2016, at 10:30 AM, Amy Rouinfar <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's discuss this at design meeting @schmitzwarehttps://github.com/schmitzware.

##

**Comment by schmitzware** [comment]
For the next developer, the place to start is in common/model/QuestionAnswer & /common/view/EditNumberDisplayNode.js.  The node is using SCENERY_PHET/NumberDisplay which, I'm guessing, will need to be expanded to allow for changing the number of decimal places (see note above).

**Comment by pixelzoom** [comment]
The new implementation (see new Shopping screen) behaves as desired, see screenshot below. No plans to fix the old implementation, since it will eventually be deleted. Closing this issue as "will not fix".

![screenshot_126](https://cloud.githubusercontent.com/assets/3046552/22161684/c499ba80-df08-11e6-85b7-16ed5d6f11e1.png)
