### ISSUE TITLE
Add 3rd decimal for Scale cost display

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#44]
From the design doc:
On the scale, a third decimal place will appear in gray when the price does not terminate at 2 decimal places. (see mockups in the design doc)

**Comment by schmitzware** [comment]
For the next developer, you're on your own on this one. :)  Start looking at common/shopping/view/ScaleNode.js.  This has a Text node ("valueText") which may need to either be extended to support multiple colors (yuck!) or maybe paired with a second Text node which only appears when needed (my suggestion).

**Comment by pixelzoom** [comment]
The design document (subsection "Rounding") currently says:
>  However, a third decimal place will be added to the scale’s Cost readout when the price does not terminate at 2 decimal places. The third decimal place will be gray, and only visible when needed, despite being shown in all mockups below.

Related to that paragraph, the design document has 2 unaddressed comments from me:
> Beside being relatively difficult to implement for the scale... Is anyone concerned that showing different values on the scale vs number line for the same data point might be a little confusing?

> Decided to discuss this at design meeting. Might be a good idea to add 3rd decimal place for cost number line, when needed. And should marker editor be able to enter 3 decimal places for cost? Or should we just round all costs to 2 decimal places and use that for comparisons?

Later in the design document (subsection "Thoughts for Teachers") it says:
> Price on scale is _truncated_.

December 8, 2016 (issue "Round") meeting notes in the design document say:
> Cost: Enter up to 3 decimal places, gets rounded to nearest cent.
> 
> Nearest neighbor rounding (5 rounds up)
> 
> Add note in Teacher tips about model simplification and direct to Proportion Playground
> 
> Show extra decimal place on scale - truncate at thousandths place, not rounded

So there's lots of conflicting information here. 

We cannot enter cost to 3 decimal places, since we discovered that having different numbers of decimal places for marker editor numerator and denominator causes problems. We're currently using 2 decimals places for all values entered via the keypad. 

And are we showing the extra decimal place on the scale? Always, or only when needed? 

@arouinfar clarification needed on this. High priority because I'm in the middle of implementation.

**Comment by pixelzoom** [comment]
If the scale is showing this extra decimal place, the number line will not be showing it. Is that confusing? It's certainly going to be problematic to implement, because the 'erase' functionality of the number line will have difficulty matching a marker to what's on the scale.

**Comment by arouinfar** [comment]
@pixelzoom the extra digit on the scale would only apply to the Shopping Lab, not the Shopping screen. 

I will review your comments more thoroughly and reply when I can, but I wanted to point out that this is an issue for the Shopping Lab screen -- not sure if that effects the priority.

**Comment by pixelzoom** [comment]
I'm not implementing separate scales for each screen - the same scale must be usable in both shopping screens.

**Comment by pixelzoom** [comment]
I will proceed with no extra digit on the scale.  But that may mean significant changes (and thus more time) when I implementing the Shopping Lab screen.

**Comment by arouinfar** [comment]
@pixelzoom you've made an excellent point. I can think of two differences between the scale in in the Shopping screen and the scale in the Shopping Lab screen.
* Shopping Lab has collapsible price.
* Shopping Lab shows 3rd decimal place on price, when non-zero.

I think we should have a deeper discussion around this at design meeting to see if we can unify the implementation of the scale across both screens. This may require further changes to what you've done now, but it would apply to both screens.

**Comment by pixelzoom** [comment]
FYI... I've already implemented the "collapsible price" as an optional feature, so it's trivial to turn it on for the Shopping Lab screen only.

**Comment by arouinfar** [comment]
Discussed at 2/9/17 design meeting.

* Third digit can exist on both Shopping and Shopping Lab screens. 
* Third digit is gray.
* If cost is exactly divisible, then third digit is not displayed (3rd digit would never would show up on Shopping screen, but there would still be a blank space for that digit).
* Cost on scale is truncated at thousandths place (e.g. $1.2349 becomes $1.234).
* Cost on double number line markers is rounded using nearest-neighbor rounding (e.g. $1.234 is displayed on scale, and $1.23 on the corresponding marker).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/unit-rates/issues/44#issuecomment-278771573:
> • Third digit can exist on both Shopping and Shopping Lab screens.

But I believe we determined that the 3rd decimal place will never be visible on the Shopping screen, because of the rates chosen for that screen, and because rate is not variable.   Investigating the implementation, this is going to be easier to implement if I do so only for the collapsible cost display - which appears only on the Shopping Lab screen.  So before I proceed, @arouinfar please verify that there is no need for this 3rd decimal place on the Shopping screen.

**Comment by arouinfar** [comment]
@pixelzoom there's no need for the Shopping Screen to have the 3rd decimal point at all. During design meeting we decided we could live with a bit of empty space (where the third digit would never actually show up because of the 3rd point in https://github.com/phetsims/unit-rates/issues/44#issuecomment-278771573) if it simplified the implementation. Adding the third digit to just the collapsible price is preferable, so I'm glad it's turned out to be the easier route.

**Comment by pixelzoom** [comment]
Here's a dev version that implemented the 3rd decimal for cost:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.59/unit-rates_en.html?showAnswers&randomEnabled=false

Red flag number 1 was the fact that this feature is difficult to describe (see https://github.com/phetsims/unit-rates/issues/44#issuecomment-278771573). Red flag number 2 is that this was crazy complicated to implement. And I'm still not confident that I got it right.  Mixing rounding and truncating creates all kinds of challenges, not the least of which is that Javascript and PhET common code have no support for truncation.

That said... I really don't like this feature. At all.  But since it's unlikely to go away... A couple of things that I think would reduce it's potential to confuse:

1. Don't mix rounding and truncation. Use rounding for both the DNL and scale. Being consistent will make it (most importantly) easier to describe/understand and (secondarily) easier to implement.
2. Always show the 3rd decimal place. Students (and teachers for that matter) are highly unlikely to understand that the disappearing 3rd decimal means that the cost had no fractional cents. 

So I would change the specification in https://github.com/phetsims/unit-rates/issues/44#issuecomment-278771573 to read:

* Third digit is used on Shopping Lab screen. 
* Third digit is gray.
* Third digit is always displayed, even if there are no fractional cents.
* Cost on scale is rounded to 3 decimals (e.g. $1.2349 becomes $1.235).
* Cost on DNL is rounded to 2 decimals (e.g. $1.2349 becomes $1.24).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/unit-rates/issues/44#issuecomment-278771573, @arouinfar said:
> • Cost on scale is truncated at thousandths place (e.g. $1.2349 becomes $1.234).
> • Cost on double number line markers is rounded using nearest-neighbor rounding (e.g. $1.234 is displayed on scale, and $1.23 on the corresponding marker).

I wanted to point out a problem here.  If the value is $1.2349, the scale will display $1.234.  But the DNL will display $1.24, _not_ $1.23, because the DNL is using rounding of the model value, not the value that the scale is displaying.  The DNL has no ability to access the scale's value.

@arouinfar please comment.

**Comment by pixelzoom** [comment]
Here's an example that is making this difficult:

1. Shopping Lab
2. Purple Candy
3. Rate = 1:5
4. 3 bags on the scale

Each bag of purple candy is 0.4 pounds.  One would think that 3 bags is therefore 1.2 pounds. But not with good old Javascript, where 3 * 0.4 = 1.2000000000000002 pounds.   So for this scenario, the marker ends up being $0.24000000000000005/1.2000000000000002, which with rounding becomes $0.24/1.2 (which is what we want).  But the scale sees $0.24000000000000005 so the cost is not exactly 2 decimal places, and we end up showing '0' as the 3rd decimal (which we don't want to do).  So now I have to try to account for floating point error, doubly difficult when mixing rounding and truncation.  I'm currently trying to handle this by rounding to 10 decimals places before truncating, but $0.24000000000000005 becomes $0.2400000001, which is still not exactly 2 decimal places.  Guess I'll need to try truncating to 10 decimal places, then truncating to 3 decimal places.

**Comment by pixelzoom** [comment]
Here's a dev version which attempts to address the problem noted in https://github.com/phetsims/unit-rates/issues/44#issuecomment-281846066.

http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.60/unit-rates_en.html?showAnswers&randomEnabled=false

I'm now truncating twice. First I'm truncating to 10 decimals, to determine whether the 3rd decimal should be displayed (e.g. $0.24000000000000005 becomes $0.2400000000). Then I'm truncating to 3 decimals for the cost displayed on the scale.  Not entirely confident that this addresses the problem, but I haven't encountered a problem yet.

**Comment by arouinfar** [comment]
> I wanted to point out a problem here. If the value is $1.2349, the scale will display $1.234. But the DNL will display $1.24, not $1.23, because the DNL is using rounding of the model value, not the value that the scale is displaying. 

@pixelzoom using nearest-neighbor rounding, $1.2349 would become $1.23 when rounded to the nearest hundredths place (the thousandths place would need to be >= 5 to round up to $1.24). The motive behind showing the truncated value on the scale is so that there's not a mismatch between the rounded value on the DNL and the cost on the scale. 

Returning to the $1.2349 example -- if we rounded the value on the scale to the nearest thousandths place, it would show $1.235. Rounding the model value ($1.2349) to the nearest hundredths place on the DNL would show $1.23. A student would expect that $1.235 would round to $1.24, so this will look wrong.

> 1. Don't mix rounding and truncation. Use rounding for both the DNL and scale. Being consistent will make it (most importantly) easier to describe/understand and (secondarily) easier to implement.

The example above is exactly why we need to mix rounding and truncation if the DNL and scale have a different number of decimal places. If we round the model value to the thousandths place on the scale, and to the hundredths place on the DNL, there will be times where the there's an apparent mismatch.

> 2. Always show the 3rd decimal place. Students (and teachers for that matter) are highly unlikely to understand that the disappearing 3rd decimal means that the cost had no fractional cents.

I would be fine with both the DNL and scale showing the cost rounded to the nearest thousandths place. This would remove the need for truncation altogether, which seems to be problematic. With the wider DNL, there should be enough room to accommodate the extra digit. However, I would want to hear feedback form @amanda-phet before making this decision, as this is a bit outside of my pedagogical wheelhouse.

**Comment by pixelzoom** [comment]
@arouinfar said:
> using nearest-neighbor rounding, $1.2349 would become $1.23 when rounded to the nearest hundredths place

Ah, right you are. Goes to show how confused I've become trying to implement this feature.

> I would be fine with both the DNL and scale showing the cost rounded to the nearest thousandths place.

At this point I'm very concerned about making to changes to the DNL. But if that's the direction you want to go...

**Comment by pixelzoom** [comment]
... and perhaps we don't need to change anything. Test drive http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.60/unit-rates_en.html?showAnswers&randomEnabled=false

**Comment by arouinfar** [comment]
> At this point I'm very concerned about making to changes to the DNL. But if that's the direction you want to go...

Good point @pixelzoom. I wasn't thinking about what implications it would have on the marker editor, so I'd rather not go there if we don't have to. I will take dev.60 for a test drive and let you know what I think.

**Comment by pixelzoom** [comment]
@arouinfar Could you please identify a set of "test scenarios" for verifying that this feature is correct? (Like what I described in https://github.com/phetsims/unit-rates/issues/44#issuecomment-281846066.)  I had a difficult time with that, and stumbled across test cases by accident.  I suspect that will also be useful for @phet-steele during RC testing.

**Comment by amanda-phet** [comment]
I just played with dev.60, and on the shopping lab screen, the appearing and disappearing 3rd decimal seemed very intuitive to me. If it existed, it meant that dollars/apples divided evenly, but if it popped up there would be rounding involved. It seems very helpful to me so it's clear when the rate is rounded. 

The DNL should always only be rounded to the nearest hundredth, since we are talking about currency.

**Comment by arouinfar** [comment]
Thanks @amanda-phet! I think dev.60 looks really smooth, and I agree that the third digit seems intuitive.

@pixelzoom everything looks correct to me. I brute-force checked every combination of spinner values for a single bag of apples. The cost on the scale was always properly truncated and the cost on the DNL was always correctly rounded. I think it's reasonable to assume your algorithm has done the trick! Not sure if there's any thing else that you need to take care of on  your end, so sending it back to you @pixelzoom.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/unit-rates/issues/44#issuecomment-282055169:
> @arouinfar Could you please identify a set of "test scenarios" for verifying that this feature is correct? 

@arouinfar I think you were doing a brute-force verification of this. Can you suggest a set of test scenarios that would be sufficient to verify this feature in the future?  That would be useful for RC testing, and future maintenance.

**Comment by arouinfar** [comment]
@pixelzoom I can think of a few useful scenarios to test, but they're really just a sub-set of using brute force. 

There's a Unit Rates Google Sheet in the sim folder on drive that may be useful:
https://docs.google.com/spreadsheets/d/16YQXC5nPOmTyPVx2br_DNpp7KqhdbsZ7i0qDyU54i_A/edit#gid=435952327

The first tab is "Shopping Lab - 20x20 spinner".  In this tab, there are several tables containing the costs for all combinations of the spinners (numerators in columns, denominators in rows). The most relevant tables would be starting on
* A1: Unit Rate
* A23: Cost of 1 bag of apples (all yellow cells will have 3rd digit visible)
* A45: Cost of 1 bag of carrots
* A67: Cost of 1 bag of purple candy

The general procedure would be:
* Pick any scene, and place one bag on the scale. 
* Pick a few denominators (recommendations below), and cycle through $1-20 in the numerator with one bag on the scale. 
* For each rate, compare the cost on the scale to the values in the corresponding row in the Google Sheet to verify that the cost has been properly truncated. 
* For each rate, verify that the corresponding value on the DNL has been correctly rounded (using nearest-neighbor rounding) to the hundredths place. 

I would recommend the following denominators:
* 9: Most costs will have a repeating decimal
* 17: Most costs will look irrational 
* 20: All costs will be exactly divisible, so the 3rd digit should never be visible.

**Comment by pixelzoom** [comment]
@arouinfar Great, that will be useful.  

@phet-steele assigning to you to take a look at the above info, for purposes of RC testing.  Feel free to close when you've had a look.

**Comment by pixelzoom** [comment]
@phet-steele Reminder that you may want to glance at this issue when dev testing this feature of the scale.  Then you can close this issue.

**Comment by phet-steele** [comment]
> @phet-steele Reminder that you may want to glance at this issue when dev testing this feature of the scale. Then you can close this issue.

Oh believe me, I have been. 😄  Still looking at it.

**Comment by phet-steele** [comment]
Things look to be working! Haven't noticed a discrepancy in three days.
