### ISSUE TITLE
Correctly entered Unit rate should include the "1" in the denominator

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/unit-rates#48]
I had recalled that we were going to be explicit about the 1 unit in the denominator of the unit rate, either before it was entered, after, or both? So box on top then "1 Apple" on bottom? 

![image](https://cloud.githubusercontent.com/assets/5096804/18194860/c802887c-70a5-11e6-85d6-0864ac9475cb.png)

Amy, am I correct in thinking this should have a 1? Can you elaborate on what decision was for this?

**Comment by arouinfar** [comment]
@kathy-phet there should not be a 1 in the denominator while the question is unanswered/incorrect , so your screenshot is correct. However, once the unit rate has been correctly answered, the denominator should read "1 Apple" to help emphasize that the unit rate is the cost for one item. We chose not to include the 1 in the denominator for the question itself because we thought that gave away too much information initially.

@schmitzware please update correctly entered unit rate challenge prompts so that the denominator says "1 [item]". Do not make any change to the unanswered/incorrectly answered unit rate prompts. The one should not appear in the denominator until the prompt is correct.

**Comment by amanda-phet** [comment]
Why would it be harmful to have 1 in the denominator before answer a question? If anything, it seems like it might make the challenge prompt clearer.

**Comment by arouinfar** [comment]
> Why would it be harmful to have 1 in the denominator before answer a question?

@amanda-phet it's not harmful, per se. However, including a one in a denominator while the prompt is unanswered/incorrect reveals that the unit rate is per item. If we want students to discover this information, it's probably better not to include the one in the denominator.

**Comment by kathy-phet** [comment]
I do remember this conversation and reasoning as Amy R is describing it, about not showing the 1 in the denominator until they submit their answers.

**Comment by amanda-phet** [comment]
I didn't know you wanted them to discover what a unit rate was (it's not in the learning goals and there are no meeting notes about it). If that's the case, I don't think showing the 1 after entering the correct answer will help them _discover_ it, because they need to correctly calculate the unit rate first in order to see the 1 in the ratio...

**Comment by arouinfar** [comment]
@amanda-phet I wouldn't say that it was an explicit learning goal, but I do remember having a conversation about this particular behavior when Susan first suggested we display the correct answers in a fraction like "$X.XX/Y items". I found the discussion summarized in the meeting notes from <a href="https://docs.google.com/document/d/1D4FBgMwvvQvo_jITN5a675KWMxseWiMZ-oN0rd7nG9A/edit#heading=h.fxe1drmxz7se">2/23/16</a> under "Representation of unit rate".

**Comment by amanda-phet** [comment]
Thanks for pointing out the conversation in the meeting notes. I guess I agree with Susan then that the 1 should be explicit because students don't often make that connection themselves, and I still think that if they need to correctly calculate the unit rate before seeing the 1 in the ratio, they already know that the unit rate is price for 1 apple. I will add this as something to look for in interviews.

**Comment by arouinfar** [comment]
Self-assigning to look out for this in interviews. @schmitzware please implement as described earlier.

> @schmitzware please update correctly entered unit rate challenge prompts so that the denominator says "1 [item]". Do not make any change to the unanswered/incorrectly answered unit rate prompts. The one should not appear in the denominator until the prompt is correct.

**Comment by schmitzware** [comment]
Just adding this for the next developer benefit. This functionality is not implemented (as it was a late to the game as far as design changes).  All the other Challenge prompts are set up at creation time, then just made invisible. They're then made visible once a correct answer is entered. This one will be a bit different as it will always be visible, then the text changed when a correct answer is given. 

There is a 'onCorrectAnswerCallback' which is passed down (search for it). One way (not necessarily the best) would be to implement this one-off up in the ShoppingModel where this call back is implemented. That would probably be the easiest but perhaps not the correct way to handle this.

**Comment by pixelzoom** [comment]
@arouinfar Related to #100... Should the denominator be "1 pound" or "1 lb" for the "candy" scene?

**Comment by arouinfar** [comment]
1 pound

**Comment by pixelzoom** [comment]
Done. Examples:

![screenshot_204](https://cloud.githubusercontent.com/assets/3046552/19197739/bf52540c-8c78-11e6-9f12-27f02ce13426.png)

![screenshot_203](https://cloud.githubusercontent.com/assets/3046552/19197747/c75983f0-8c78-11e6-8ccc-de0b53a1459d.png)

Closing.

**Comment by arouinfar** [comment]
👍

**Comment by pixelzoom** [comment]
Whoopsie... Adding 1 to the Unit Rate denominator messed up the denominator of the other challenges. Fixed in the above commit.
