### ISSUE TITLE
Manual entry should override existing line

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/unit-rates#50]
Amanda was demoing the Unit Rate sim, and it seemed odd when she entered a value in one of the boxes and the whole line entry disappeared (because it happened to be an existing line). I think perhaps it would have seemed more natural for it to just jump to that spot (even though there was already a line there). You can always get rid of it, or enter another number that will jump it to another spot. 

@arouinfar - Can you take a look at that behavior and comment?

**Comment by arouinfar** [comment]
@kathy-phet during the interview, the student attempted to manually add a line that already existed, but I don't remember the outcome. I'll review the screen capture, and then make a recommendation.

**Comment by arouinfar** [comment]
We discussed this in the 9/22 meeting. If a student manually enters line that already exists on the double number line, it will simply replace the previous line. While the student will lose a little work, it is far more frustrating if nothing appears to happen.

**Comment by arouinfar** [comment]
For clarification of the desired behavior, consider this example.
- Start sim
- Go to Shopping screen
- Put 3 bags of apples on the scale, the double number line will look like this:
  ![image](https://cloud.githubusercontent.com/assets/8419308/19101329/a0e3f246-8a84-11e6-952b-6c69b28cdf86.png)
- Use maker editor to place a marker at 15 apples. The marker at (15, $7.50) will be replaced, and the student will need to re-enter $7.50.
  ![image](https://cloud.githubusercontent.com/assets/8419308/19101342/ca207936-8a84-11e6-9a76-fd4ad84c581c.png)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/unit-rates/issues/50#issuecomment-251581257, @arouinfar said:
> The marker at (15, $7.50) will be replaced, and the student will need to re-enter $7.50.

I'm confused here, because I didn't see any request to delete an existing marker. 

The new implementation (see [1.0.0-dev.36](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.36/unit-rates_en.html)) currently does not replace markers like this.  And I'm wondering if it needs to, because the marker editor fully covers an existing marker.  For example, if we have this marker for Apples:

![screenshot_127](https://cloud.githubusercontent.com/assets/3046552/22162951/1ddcad1e-df0e-11e6-8ed3-1b6f8c204b4d.png)

If I enter denominator '8' in the marker editor, the editor moves to fully cover the existing 4/8 marker:

![screenshot_128](https://cloud.githubusercontent.com/assets/3046552/22162972/31399ce6-df0e-11e6-981c-261f8f756965.png)

If the user enters '4', then there's no reason to delete the existing marker; duplicate markers are simply ignored.

But if the user enters numerator '3', the editor will move to ?/3.  In this case, I don't see any request to delete the 4/8 marker.  Doing so would certainly complicate things, and I'm not sure what learning goal it would serve.  

@arouinfar can you please clarify? Is the behavior in [1.0.0-dev.36](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.36/unit-rates_en.html) as desired?

**Comment by pixelzoom** [comment]
High priority because I'm trying to wrap up the Shopping screen.

**Comment by arouinfar** [comment]
@pixelzoom dev.36 looks good to me. No need to delete the existing marker because duplicates are not considered and the marker editor completely obscures the marker behind it.
