### ISSUE TITLE
tomato is not a vegetable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#51]
The "Shopping" screen has 3 categories of items: fruits, vegetables and candy.   Tomato is a _fruit_, and it's currently in the vegetable category.  Admittedly not a big deal for STEM, but wrong nonetheless.  Perhaps you should avoid the issue altogether by replacing tomato with a vegetable.

**Comment by arouinfar** [comment]
@pixelzoom I am aware that a tomato is a fruit. However, we do not explicitly call the screen "vegetables" other than in internal documentation.

**Comment by ariel-phet** [comment]
Could change the internal documentation to "produce" for the vegetables :)

**Comment by arouinfar** [comment]
We could @ariel-phet. However, "Fruit" and "Produce" seems more confusing, since fruit is produce, after all.

We wanted to choose items of produce that had a variety of different colors, and would be recognizable around the world. That is why tomatoes made it into the "vegetable" scene, despite not being a vegetable.

**Comment by pixelzoom** [comment]
@arouinfar wrote:

> However, we do not explicitly call the screen "vegetables" other than in internal documentation.

Oh come on... There's an obvious attempt to put things in categories here, and users will pick up on it immediately.  There's clearly a "vegetables" category.  If there's not, then why have 3 different scene buttons?

According to https://en.oxforddictionaries.com/explore/is-a-tomato-a-fruit-or-a-vegetable:

> The confusion about 'fruit' and 'vegetable' arises because of the differences in usage between scientists and cooks.  Scientifically speaking, a tomato is definitely a fruit. ... As far as cooking is concerned, some things which are strictly fruits, such as tomatoes or bean pods, may be called 'vegetables' because they are used in savoury rather than sweet cooking.

**Comment by arouinfar** [comment]
@pixelzoom sure, there are categories, but cucumbers are also technically a fruit. A lot of what we might consider "vegetables" (used in savory applications) are botanically fruits like peppers, eggplant, green beans, and squash. Tomatoes are just the most widely known fruit that gets lumped in with vegetables.

If we want to make the options botanically accurate to match the implicit "vegetable" category, then we would need to replace tomatoes AND cucumbers. I'll reiterate that the goal was to pick easily distinguishable items of produce with a variety of colors.

**Comment by pixelzoom** [comment]
OK. Closing as "won't fix".

**Comment by arouinfar** [comment]
So it's on the record, I'll answer this as well:

> why have 3 different scene buttons?

The scenes are scaffolded. Fruit bags open up so that individual items can be removed from the scale, and the challenge prompts are much simpler. "Vegetable" bags do not open, and the challenge prompts have added difficulty. The candy scene is used to approximate a more continuous scenario ($/lb rather than $/item).

@pixelzoom I have made a note in the design doc to clarify the fruit/vegetable distinction in the Teacher Tips.
