### ISSUE TITLE
Outstanding issues

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#54]
In addition to the existing GitHub issues that are assigned to me

https://github.com/phetsims/unit-rates/issues/assigned/schmitzware

some of these are design doc changes which I never got around to implementing & some of these are internal things which I would like to have done differently or cleaned up a bit more. 

Shopping
- First challenge question should have visible 1 in denominator (https://github.com/phetsims/unit-rates/issues/48).
- (*) shopping/model/Challenges, function generateQuestionsAnswersForItem could probably be done better. This thing has always bothered me.

Racing Lab
- Need to disable/enable 1/2 car selection buttons on race start/finish
- Interacting with any UI component needs to stop the race and reset it to the beginning.
- Keypad background needs to be set to something non-transparent.
- Keypad needs to be positioned (or resized?)  better. There was talk of a horizontal keypad also.
- Drag area needs to be larger for the finish flag, Should be large enough to cover flag, green arrows & milage marker)
- Car speed need to be set (100 mph = 0.25 seconds, see RacingLabConstants : RACING_DT_SCALE in ) Ariel was going to review this also.
- From the design doc - there should be a unique set of markers for each rate (mile/hour) combination. Right now there is a single array for all markers added. So, there needs to be separate marker arrays that are swapped out when the rate changes.  (Ping me if you need more clarification)
- (*) common/view/URNumberLineNode, function setPixelLength is a bit janky to put it mildly. This is called when the track length gets changed by the user. It is responsible for showing/hiding/moving markers that are off the end of the number line. It works but is a pain in the a$$ to work with if the dimensions of the number line change. It would probably be a good thing if the variable "xAxisLength" went away somehow.

(*) bigger ones

**Comment by pixelzoom** [comment]
Other things I noticed:

All screens:
• Dilate touchArea for accordion box expand/collapse buttons
• Dilate touchArea for 'edit' buttons
• Dilate touchArea for 'erase' button
• Disable 'erase' button when there's nothing to erase
• Numeric values on double number line are incredibly small, I almost can't read them on my MacBook. Have these been vetted on iPad or iPad Mini?
• Test multitouch scenarios (e.g. change scenes while dragging a bag of apples, etc.)

Shopping:
• Same challenge often appears twice in a row, that seems undesirable. (Maybe in `Challenges.refresh`, but there's also some duplication in `ChallengeData`.)
• Height of the combo box changes depending on which scene is selected

Shopping Lab:
• Rate control panel overlaps "Return to shelf" button with `?stringTest=long`.

Shopping, Shopping Lab:
• Disable "Return to shelf" button when there's nothing on the scale
• I was able to get some odd layouts for things on the scale, inspect the algorithm

Racing Lab:
• When switching scenes (1 vs 2 cars), should the 2nd car's UI elements fade in/out (ala scene changes in hookes-law)?
• The finish flag needs `cursor:'pointer'`, there's no cursor until you start to drag it.
• Should you be able to drag the finish flag to the left of the car? (E.g., when the car is at the finish line) Or should the car get pushed back with the flag? 
• When rate is 200 miles / 1 hour, the car finishes in 1.02 hours, that doesn't seem correct. Similar error with other values.
• Disabling the "return to start" button, rather than making it invisible, would be more PhET-like.
• "Start race" button should be disabled when cars are at finish line.
• Reset All button is in a different place than other screens

**Comment by arouinfar** [comment]
To address some of @pixelzoom's comments

>  Same challenge often appears twice in a row, that seems undesirable. (Maybe in Challenges.refresh, but there's also some duplication in ChallengeData.)

I've also noticed this. Perhaps the four sets of challenge prompts for each item could be randomly ordered on startup (rather than randomly pulling one set on Challenges.refresh). That way, the challenge refresh button would never repeat the same sets of prompts. For example, on startup the apple prompts are randomly ordered as set D, B, A, C (using the naming from the design doc). Students would first see problem set D, and upon Challenges.refresh set B would appear, and so on.

> Should you be able to drag the finish flag to the left of the car? (E.g., when the car is at the finish line) Or should the car get pushed back with the flag? 

No. The car should get pushed back with the flag.

> When rate is 200 miles / 1 hour, the car finishes in 1.02 hours, that doesn't seem correct. Similar error with other values.

The rate spinners do not have the correct ranges. From the 9/8/16 meeting notes, we decided that the miles spinner ranges 20-100 mi, and increases in 5 mi increments. The hour spinner ranges 1-10 hours, and increases in 1 hr increments.

> Disabling the "return to start" button, rather than making it invisible, would be more PhET-like.

Good suggestion. I agree.

> "Start race" button should be disabled when cars are at finish line.

Not exactly... we discussed this in a recent meeting, but unfortunately I can't find it in the notes. We discussed two different behaviors. If "return to start" is pressed, the car returns to the staring line but remains static. If "go" is pressed, the car returns to the start and immediately starts repeating the race.

**Comment by schmitzware** [comment]
Fixed:
- The finish flag needs cursor:'pointer', there's no cursor until you start to drag it.
- When rate is 200 miles / 1 hour, the car finishes in 1.02 hours, that doesn't seem correct. Similar error with other values.
- Reset All button is in a different place than other screens
- Fixed Racing Lab spinner ranges

Additional Notes:
- Height of the combo box changes depending on which scene is selected - most likely do to the different image heights
- Disabling the "return to start" button, rather than making it invisible, would be more PhET-like. This was a design decision though I didn't bring up your point (not really being aware of it, honestly)
- Mobile untested
- Shopping/Lab: I was able to get some odd layouts for things on the scale, inspect the algorithm.  see https://github.com/phetsims/unit-rates/issues/36

**Comment by pixelzoom** [comment]
Next step is to create individual issues for the things above (my list and @schmitzware's).

**Comment by pixelzoom** [comment]
My list has been split out into the above issues.

**Comment by pixelzoom** [comment]
@schmitzware's list has been split out into the issues above.

Closing.
