### ISSUE TITLE
issues with keypad on Racing Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#94]
From #54 (Outstanding issues):

@schmitzware said:

> • Keypad background needs to be set to something non-transparent.
> • Keypad needs to be positioned (or resized?) better. There was talk of a horizontal keypad also.

@arouinfar Please specify, or point me to the relevant section of the design doc.

**Comment by arouinfar** [comment]
@pixelzoom, for now the number pad location in dev.22 is okay, which is similar to this screenshot (sizing of the number pad in the mockup is a little off -- dev.22 size is good). The background color of the number pad should be made an opaque gray since it's being layered over other components.
![image](https://cloud.githubusercontent.com/assets/8419308/19058553/762f2bb4-8995-11e6-88b1-02c534b2b747.png)

However, to minimize the occlusion, we have discussed the possibility of creating a horizontal number pad. This number pad has not yet been designed. A horizontal number pad may be a useful common component to have in future math sims, and it would work better with the layout of the screen.  (Obviously still work to be done with the number display and the enter button -- this is just meant to show rough layout.)
![image](https://cloud.githubusercontent.com/assets/8419308/19058578/adf481c0-8995-11e6-8fc4-c875b6130a57.png)

**Comment by pixelzoom** [comment]
Re the horizontal keypad - to be blunt, bad idea. The keypad should look the same throughout the sim (and preferably throughout all sims).  Flipping it on its side is a bandaid for bigger design issues.

Have you considered making the keypad non-modal and movable?

**Comment by pixelzoom** [comment]
@arouinfar said:

> The background color of the number pad should be made an opaque gray since it's being layered over other components.

I highly recommend using this same background color (opaque gray) for the keypad in _all_ screens, so that the keypad looks the same everywhere.  Would that be OK?

**Comment by arouinfar** [comment]
> Have you considered making the keypad non-modal and movable?

The discussion around a horizontal keypad was very brief, and quickly tabled because DS was on his way out. We also hadn't yet had the discussion around a global dialog component. I think a non-modal, movable keypad would be ideal.

> I highly recommend using this same background color (opaque gray) for the keypad in all screens, so that the keypad looks the same everywhere. Would that be OK?

Agreed @pixelzoom. Let's use an opaque gray background on all screens.  

Reassigning to @pixelzoom to take care of the background color. We'll likely need to discuss the non-modal, movable keypad in design meeting.

**Comment by pixelzoom** [comment]
Keypad background change to RGB=230,230,230, as in mockup above.

Back to @arouinfar to address design issues.

**Comment by arouinfar** [comment]
Challenge prompts -- keypad remains where it is now
Marker editor -- keypad pops up beneath (or above, if car 2) the edit button

**Comment by arouinfar** [comment]
@pixelzoom why is this reassigned to me? Do you want me to create some mockups based on our discussion yesterday?

**Comment by pixelzoom** [comment]
Must've fat fingered the Assignees list. Unassigning @arouinfar, I have all the info I need.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/unit-rates/issues/94#issuecomment-252077568:
> Challenge prompts -- keypad remains where it is now
Marker editor -- keypad pops up beneath (or above, if car 2) the edit button

The described behavior is implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.47/unit-rates_en.html?showAnswers&randomEnabled=false

@arouinfar please review.

**Comment by arouinfar** [comment]
👍
