### ISSUE TITLE
calibrate car speed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#95]
From #54 (Outstanding issues):

@schmitzware said:

> Car speed need to be set (100 mph = 0.25 seconds, see RacingLabConstants : RACING_DT_SCALE in ) Ariel was going to review this also.

**Comment by pixelzoom** [comment]
@ariel-phet What do you know about this issue?

**Comment by ariel-phet** [comment]
@pixelzoom basically we wanted the slowest and fastest speeds to look decent. I believe @arouinfar has some powerpoint animations to help calbirate

**Comment by arouinfar** [comment]
@pixelzoom here's a comparison of the maximum (100 mi/1 hr) and minimum (20 mi/10 hr) speeds. The .gif compression makes things look a little jumpier than the original powerpoint.

![car_speed](https://cloud.githubusercontent.com/assets/8419308/19058138/30a5b8cc-8992-11e6-88a2-153dec420ee4.gif)

If we make the 100 mph car take much longer (0.3 s or 0.5 s, for example) the slowest car gets dragged out quite a bit, since there's a factor of 50 difference.

**Comment by pixelzoom** [comment]
@arouinfar more questions:

(1) So there's a 50x difference between the slowest and fastest speeds, but you don't want there to be a 50x difference in the animation time, is that correct?  

(2) Are you concerned that some students may compare N mph and 2N mph (where N could be any value between 2 and 50) and notice that 2N mph is not twice as fast in wall time? 

(3) What is the desired function that computes animation time as function of speed?

**Comment by arouinfar** [comment]
@pixelzoom  I think my previous comment was a bit unclear, perhaps because I wrote the max/min speeds in terms of spinner values (100/1, 20/10).

> (1) So there's a 50x difference between the slowest and fastest speeds, but you don't want there to be a 50x difference in the animation time, is that correct?

No, we definitely want the animation speed to scale with the speed. Max speed = 100 mph, scaled to 0.25s. Min speed = 2mph, scaled to 12.5s. There is a factor of 50 difference between the speeds and the times.

> (2) Are you concerned that some students may compare N mph and 2N mph (where N could be any value between 2 and 50) and notice that 2N mph is not twice as fast in wall time?

Absolutely. That's why we want the animation speed to accurately scale.

> (3) What is the desired function that computes animation time as function of speed?

100 mph = 0.25 s; all other speeds scaled proportionally. To put it mathmatically:
time to finish line = (100/rate)*0.25s

**Comment by pixelzoom** [comment]
Got it, thanks for the clarification.

**Comment by pixelzoom** [comment]
If it takes 0.25 seconds to move 200 miles at 100 miles/hr,  then it takes half that time (0.125 seconds) to move 100 miles at 100 miles/hr.   Therefore 0.125 seconds of simulation time is equivalent to 1 hour of "race time", and 1 second of simulation time is equivalent to 8 hours of "race time".  So in our model's `step` function,  the conversion from simulation time (seconds) to race time (hours) is:

```js
step: function( dt ) {
  // race time, in hours. 1 sec of sim time is equivalent to 8 hours of race time
  var deltaRaceTime = Util.linear( 0, 1, 0, 8, dt );
}
```

**Comment by pixelzoom** [comment]
Car speed and timer are calibrated in [1.0.0-dev.51](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.51/unit-rates_en.html?showAnswers&randomEnabled=false).

1 second of sim time is equivalent to 8 hours of race time. Completing a 200 mile race at a rate of 100 miles/hour would take 2 hours.  And 2 hours of race time occurs in 0.25 seconds of sim time. 

@arouinfar please verify.

**Comment by arouinfar** [comment]
Looks great! Thanks @pixelzoom.
