### ISSUE TITLE
unique set of markers for each rate (mile/hour) combination

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#96]
From #54 (Outstanding issues):

@schmitzware said:

> Racing Lab
> From the design doc - there should be a unique set of markers for each rate (mile/hour) combination. Right now there is a single array for all markers added. So, there needs to be separate marker arrays that are swapped out when the rate changes. (Ping me if you need more clarification)

@arouinfar Can you point me to the specification for this?

**Comment by arouinfar** [comment]
@pixelzoom this was discussed in the 9/1/16 design meeting notes, but isn't (yet) described in the main body of the doc.

The idea is that students may spend a decent amount of time building up their double number line, and we don't want them to lose their work if they change the rate or track length. Essentially, we want the state to be saved for each unique rate. 

For example, assume the sim is freshly started. The student sets Rate 1 = 50mi/2hrs and the track length = 200 mi. The student then manually adds lines to the double number line at 25mi/1hr, 50 mi/2hrs, 100 mi/4hrs, and 200 mi/8hrs. If the student changes the track length to 50 miles, the lines at 100 miles and 200 miles will disappear from the double number line, but reappear if the track is lengthened again.  If the student changes the rate, the double number line will clear (because nothing had previously been added to the double number line at that new rate). If the student goes back to the rate of 50mi/2hrs, the double number line is repopulated with their previous work. However, this does not apply to equivalent rates like 100mi/4hrs.

**Comment by pixelzoom** [comment]
@arouinfar said:

> Essentially, we want the state to be saved for each unique rate.

What is a "unique rate"?  Is it a specific rate value? Or is it a specific pair of numerator and denominator values?  In the former case, 80/2 and 40/1 (both the same rate of 40mph) would share state.  In the latter case, 80/2 and 40/1 would each have their own state.

**Comment by arouinfar** [comment]
@pixelzoom 

> If the student goes back to the rate of 50mi/2hrs, the double number line is repopulated with their previous work. However, this does not apply to equivalent rates like 100mi/4hrs.

A "unique rate" is a specific pair of numerator and denominator values, which does not consider equivalent rates. Thus, 80/2 and 40/1 would have their own independent states. Every spinner combination has its own state.

**Comment by pixelzoom** [comment]
Related info from https://github.com/phetsims/unit-rates/issues/127#issuecomment-252067446:
>  For each setting of miles/hours, save what's on the number line, and position of the finish flag (see #96). Erase button on number line erases the number line markers for just that miles/hours setting.

**Comment by pixelzoom** [comment]
At 2//9/17 design meeting, we decided to hold off on this feature, due to a few concerns:

(1) Behavior is different than Shopping Lab screen, and may confuse user.
(2) User may think that changing rate has erased their markers.
(3) Responsiveness of rate spinners will be compromised by having to save/restore markers.
(4) Solutions that increase responsiveness of spinners will impact memory footprint.
(5) Learning goals may be met with behavior similar to Shopping Lab screen.
(6) Original motivation for this feature ("user will game the system") may not be an issue; if they figure out how to "game the system", they have learned something.
(7) Implementation is non-trivial, represents a big part of Racing Lab screen.

So I'm going to make Racing Lab work similar to Shopping Lab, with one major difference: when rate is changed, the _denominator_ (hours) for markers will be updated.  Interviews will decide whether this solution is sufficient.  If not, nothing in the implementation precludes implementation of the feature as originally described.

@arouinfar please elaborate if I missed anything.

**Comment by arouinfar** [comment]
@pixelzoom thank you for this summary. I cannot think of anything else to add. 

I'm going to tag this issue for interviews. Please reassign this to me once you are finished.

**Comment by pixelzoom** [comment]
In [1.0.0-dev.48](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.48/unit-rates_en.html?showAnswers&randomEnabled=false), the denominator values (hours) for markers change when the rate is changed.  @arouinfar please verify.  If it looks good, the remaining task is interviews.

**Comment by arouinfar** [comment]
Looks good @pixelzoom! I'll tag this for interviews and leave self-assigned. Thanks!

**Comment by arouinfar** [comment]
I didn't notice any issues in interviews. Closing.
